import torch
from pykeen.pipeline import pipeline
from pykeen.triples import TriplesFactory

tf = TriplesFactory.from_path(
    path="/content/results.tsv", # Hypothetic path, generated by graphDB
)

training, testing = tf.split(random_state=42)
print(f"Entities: {len(tf.entity_to_id)}, Relations: {len(tf.relation_to_id)}")

results = pipeline(
    training=training,
    testing=testing,
    model='TransH',
    training_kwargs=dict(num_epochs=30, batch_size=2048, use_tqdm_batch=True),
    evaluation_kwargs = {"batch_size": 4096},
    model_kwargs= {
        "embedding_dim": 64,
    },
    optimizer='Adam',
    optimizer_kwargs=dict(lr=1e-3),
    random_seed=42,
    device='cuda'
)

# Persist for later
results.save_to_directory("/content/pykeen_runs/transh_run")